lastupdatecheck: 0
recentrepos:
- /home/basile/Projects/lore
- /home/basile/Projects/varek2.0
- /home/basile/Projects/react-library
- /home/basile/dotfiles
- /home/basile/notes
- /home/basile/courses/ai/assignements/Evolutionary-Optimization
- /home/basile/Projects/citaizen_arch
- /home/basile/Projects/ai_server
- /home/basile/Projects/B-PRO-600-MPL-6-1-tech3internship-basile.lamotte
startuppopupversion: 5
customcommandshistory:
- q
hidecommandlog: true
ignorewhitespaceindiffview: false
